# Generated by Django 2.1.1 on 2019-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_object_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='object_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
