# Generated by Django 2.1.1 on 2019-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180919_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='finishied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='output',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='standard_resolution',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
