# Generated by Django 2.1.1 on 2019-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20190428_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='object_count',
            field=models.IntegerField(default=0),
        ),
    ]
