# Generated by Django 2.1.1 on 2019-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190522_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='object_count',
        ),
        migrations.RemoveField(
            model_name='media',
            name='object_name',
        ),
        migrations.AlterField(
            model_name='media',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
